import type { Metadata } from "next";
import { Geist, Geist_Mono, Cinzel, Playfair_Display } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll/SmoothScroll";
import TransitionProvider from "./transition/TransitionProvider";
import LightsBackground from "./components/LightsBackground";
import TransitionOverlay from "./transition/TransitionOverlay";
import Nav from "./components/Nav/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-playfair",
});

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pl"
      className={`${geistSans.variable} ${geistMono.variable} ${cinzel.variable} ${playfair.variable}`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <div className="appWrapper">
          <TransitionProvider>
            <LightsBackground
              style={{ position: "fixed", zIndex: 45, pointerEvents: "none" }}
              burstFactor={2.5}
            />{" "}
            <Nav />
            <TransitionOverlay /> {/* przyciemnienie tła — czyta fazę */}
            {children}
          </TransitionProvider>
          <SmoothScroll />
        </div>
      </body>
    </html>
  );
}
