import type { Metadata } from "next";
import { Playfair_Display, Montserrat, Parisienne } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll/SmoothScroll";
import TransitionProvider from "./transition/TransitionProvider";
import LightsBackground from "./components/LightsBackground";
import TransitionOverlay from "./transition/TransitionOverlay";
import Nav from "./components/Nav/Nav";
import { CartProvider } from "./components/Ebooks/Cart/CartContext";
import CartDrawer from "./components/Ebooks/Cart/CartDrawer";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-header",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-basic",
});

const parisienne = Parisienne({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-decoration",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pl"
      className={`${parisienne.variable} ${montserrat.variable} ${playfair.variable}`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <CartProvider>
          <div className="appWrapper">
            <TransitionProvider>
              <LightsBackground
                style={{ position: "fixed", zIndex: 45, pointerEvents: "none" }}
                burstFactor={2.5}
              />{" "}
              <Nav />
              <TransitionOverlay /> {/* przyciemnienie tła — czyta fazę */}
              {children}
              <CartDrawer />
            </TransitionProvider>
            <SmoothScroll />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
